project:
  type: website

website:
  title: "THK-AI Research Cluster"
  description: "Forschungscluster THK-AI: Künstliche Intelligenz in der Technischen Hochschule Köln"
  site-url: "https://thk-ai.de/"
  navbar:
    left:
      - news.qmd
      - about.qmd
      - members.qmd
      - hpc.qmd
      - lehre.qmd
      - forschung.qmd
      - veranstaltungen.qmd
    right:
      - text: DE
        href: index.qmd
      - text: EN
        href: index-en.qmd
      - icon: github
        href: https://github.com/thk-ai/thk-ai
  page-footer:
    left:
      - text: "&copy; Technische Hochschule K&ouml;ln"
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd
  open-graph:
    title: "THK-AI Research Cluster"
    description: "Forschungscluster THK-AI: Künstliche Intelligenz in der Technischen Hochschule Köln"
    image: <img src="figures/logos/thk-ai-logo.png" alt="THK-AI Logo" width="400"/>
format:
  html:
    theme:
      - litera
    css: styles.css
    include-after-body: theme-toggle.html
    toc: true
    number-sections: false
    smooth-scroll: true

execute:
  freeze: auto
